### ISSUE TITLE
[Feature] Make input "args" optional

### ISSUE THREAD

**Issue by ricardo-dematos** [tj-actions/docker-run#20]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like?

When running a docker container, it will not always be required to run a command. 

Take this example:

```yaml
      - name: 'Start service container'
        id: start
        run: 'docker run --detach --rm --name ${{ steps.setup.outputs.repository_name }} --network ${{ steps.setup.outputs.github_network }} --network-alias ${{ steps.setup.outputs.repository_name }} --publish 8003:80 --health-cmd "curl -s -I -L -o /dev/null -X POST --url "http://localhost/checks/connection-check/"" --health-interval 10s --health-timeout 5s --health-retries 5 --env "HEALTH_CHECK_TOKEN=${{ secrets.HEALTH_CHECK_TOKEN }}" --env "GITHUB_ACTIONS=true" --env "CI=true" ${{ steps.setup.outputs.repository_owner }}/${{ steps.setup.outputs.repository_name }}:latest'
        shell: bash

      - name: 'Wait for service to be ready'
        id: wait
        timeout-minutes: 1
        run: 'while [ "$( docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" ${{ steps.setup.outputs.repository_name }} )" == "starting" ]; do sleep 1s; done;'
        shell: bash
```

This docker container will be running on the workflow and available to be used in other steps as a service.

P.S.:
Notice the step to ensure the docker container will be ready to be used in the next steps. This should also be considered in  this action.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
